### ISSUE TITLE
 U have android source too?

### ISSUE THREAD

**Issue by lordmen99** [Felonius-Gru/Joysale#1]
hi i want try this app, u have for android source too. please post it here too

thx

**Comment by mister-gru** [comment]
I have not android source

**Comment by lordmen99** [comment]
i am looking buy now function, i see in script web already module, but need android source

**Comment by mister-gru** [comment]
I purchase this source code.
I have only web and iOS, not Android.
Thx.

**Comment by lordmen99** [comment]
how much u purchase this source and where? i am looking for android source with buy now function in inside

**Comment by mister-gru** [comment]
https://joysalescript.com/
You can purchase here.

On Aug 23, 2017, at 9:43 AM, lordmen99 <notifications@github.com<mailto:notifications@github.com>> wrote:


how much u purchase this source and where? i am looking for android source with buy now function in inside
